call `.toSeq` method when varargs methods
prepare Scala 2.13.0-M4

varargs parameter type changed since Scala 2.13.0-M4

```
Welcome to Scala 2.13.0-M4 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_172).
Type in expressions for evaluation. Or try :help.

scala> def foo(xs: Int*): scala.collection.Seq[Int] = xs
foo: (xs: Int*)scala.collection.Seq[Int]

scala> def bar(xs: Int*): scala.collection.immutable.Seq[Int] = xs
bar: (xs: Int*)Seq[Int]

scala> val a: collection.Seq[Int] = Nil
a: scala.collection.Seq[Int] = List()

scala> foo(a: _*)
           ^
       error: type mismatch;
        found   : Seq[Int] (in scala.collection)
        required: Seq[Int] (in scala.collection.immutable)

scala> foo(a.toSeq: _*)
res1: scala.collection.Seq[Int] = List()
```

```
Welcome to Scala 2.12.6 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_172).
Type in expressions for evaluation. Or try :help.

scala> def foo(xs: Int*): scala.collection.Seq[Int] = xs
foo: (xs: Int*)Seq[Int]

scala> def bar(xs: Int*): scala.collection.immutable.Seq[Int] = xs
<console>:11: error: type mismatch;
 found   : Seq[Int] (in scala.collection)
 required: Seq[Int] (in scala.collection.immutable)
       def bar(xs: Int*): scala.collection.immutable.Seq[Int] = xs
                                                                ^

scala> val a: collection.Seq[Int] = Nil
a: Seq[Int] = List()

scala> foo(a: _*)
res0: Seq[Int] = List()

scala> foo(a.toSeq: _*)
res1: Seq[Int] = List()
```